substitutions:
  name: "esp32s3-test"
  friendly_name: "ESP32S3 Test"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "samuelkadolph.${name}"
    version: "0.1"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

logger:
  level: DEBUG

ota:
- platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret kadolph_devices_ssid
  password: !secret kadolph_devices_pass

  ap:
    ssid: "${friendly_name}"
    password: !secret fallback_ap_pass

captive_portal:

api:
  encryption:
    key: !secret esp32s3_test_key

binary_sensor:
- platform: gpio
  name: "Button"
  entity_category: diagnostic
  pin:
    ignore_strapping_warning: true
    inverted: true
    number: GPIO00

button:
- platform: restart
  name: "Restart"
  entity_category: diagnostic

light:
- platform: esp32_rmt_led_strip
  name: "Status LED"
  entity_category: diagnostic
  chipset: WS2812
  default_transition_length: 0s
  num_leds: 1
  pin: GPIO21
  restore_mode: RESTORE_AND_OFF
  rgb_order: RGB

sensor:
- platform: wifi_signal
  name: "Signal Strength"
  entity_category: diagnostic
  filters:
  - sliding_window_moving_average:
      window_size: 4
      send_every: 4
- platform: uptime
  name: "Uptime"
  entity_category: diagnostic

text_sensor:
- platform: wifi_info
  mac_address:
    name: "MAC Address"
    entity_category: diagnostic
  ip_address:
    name: "IP Address"
    entity_category: diagnostic
