substitutions:
  name: ir-blaster
  friendly_name: IR Blaster
  project_name: samuelkadolph.${name}
  project_version: "0.1"

  logging: DEBUG

  ir_pin: GPIO21

api:
  encryption:
    key: !secret api_encryption_key

  on_client_connected: [ script.execute: set_status_led ]
  on_client_disconnected: [ script.execute: set_status_led ]

captive_portal:

esp32:
  variant: esp32c6
  framework:
    type: esp-idf

logger:
  level: ${logging}

ota:
- platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret fallback_password

  on_connect: [ script.execute: set_status_led ]
  on_disconnect: [ script.execute: set_status_led ]

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # name_add_mac_suffix: true

  project:
    name: ${project_name}
    version: ${project_version}

  on_boot: [ script.execute: set_status_led ]

binary_sensor:
- platform: gpio
  name: Button
  disabled_by_default: true
  entity_category: diagnostic
  pin:
    ignore_strapping_warning: true
    inverted: true
    number: GPIO09

button:
- platform: restart
  name: Restart
  entity_category: diagnostic

infrared:
  - platform: ir_rf_proxy
    name: IR Transmitter
    remote_transmitter_id: ir_tx

interval:
- interval: 1s
  then: [ script.execute: set_status_led ]

light:
- platform: esp32_rmt_led_strip
  id: status_led
  channel_colors: RGB
  chipset: WS2812
  default_transition_length: 0ms
  num_leds: 1
  pin:
    ignore_strapping_warning: true
    number: GPIO08
  rmt_symbols: 48

remote_transmitter:
  id: ir_tx
  carrier_duty_percent: 50%
  non_blocking: true
  pin: ${ir_pin}
  rmt_symbols: 48

  on_transmit:
  - light.turn_off: { id: status_led }
  - delay: 50ms
  - light.turn_on: { id: status_led, brightness: 0.6, red: 1.0, green: 0.0, blue: 0.0 }
  - delay: 50ms
  - light.turn_off: { id: status_led }
  - delay: 50ms
  - light.turn_on: { id: status_led }
  - delay: 50ms
  - light.turn_off: { id: status_led }
  - delay: 50ms
  - script.execute: set_status_led

script:
- id: set_status_led
  then:
  - lambda: |-
      static uint32_t good_since = 0;
      if (api::global_api_server->is_connected()) {
        if (good_since && App.get_loop_component_start_time() >= good_since + 60000) {
          id(status_led).turn_off().perform();
        } else {
          good_since = good_since ? good_since : App.get_loop_component_start_time();
          id(status_led).turn_on().set_brightness(0.2).set_rgb(0.0, 1.0, 0.0).perform();
        }
      } else {
        good_since = 0;
        if (wifi::global_wifi_component->is_connected()) {
          id(status_led).turn_on().set_brightness(0.3).set_rgb(0.0, 0.0, 1.0).perform();
        } else if (wifi::global_wifi_component->is_ap_active()) {
          id(status_led).turn_on().set_brightness(0.3).set_rgb(0.5, 0.0, 0.5).perform();
        } else {
          id(status_led).turn_on().set_brightness(0.3).set_rgb(1.0, 0.0, 0.0).perform();
        }
      }

sensor:
- platform: wifi_signal
  name: Signal Strength
  entity_category: diagnostic
  filters:
  - sliding_window_moving_average:
      send_every: 5
      window_size: 5

- platform: uptime
  name: Uptime
  entity_category: diagnostic

text_sensor:
- platform: wifi_info
  mac_address:
    name: MAC Address
    entity_category: diagnostic
  ip_address:
    name: IP Address
    entity_category: diagnostic
